package knowledge.util;

import junit.framework.TestCase;

public class DistanceMathTest extends TestCase {
    public void testAutoGeneratedExpression() {
        // ((a + b) < c) && (c == 0 || a == 1)
        // knowledge.util.DistanceMath.and((knowledge.util.DistanceMath.lessThan((a+b), c)), (knowledge.util.DistanceMath.or(knowledge.util.DistanceMath.equalThan(c, 0), knowledge.util.DistanceMath.equalThan(a, 1))))"
        int a, b, c;
        a = 100;
        b = 10;
        c = 1;
        int result = knowledge.util.DistanceMath.and((knowledge.util.DistanceMath.lessThan((a+b), c)), (knowledge.util.DistanceMath.or(knowledge.util.DistanceMath.equalThan(c, 0), knowledge.util.DistanceMath.equalThan(a, 1))));
        assertEquals(111, result);
    }
}
