export SPY_CONNECTION_STRING=mysql+pymysql://root:supersecret@localhost/test

CURRENTPATH=${PWD}
cd ..
PROJECTPATH=${PWD}
SHOOTERPATH=$PROJECTPATH/shooter
SPYPATH=$PROJECTPATH/openspy
HURRICANEPATH=$PROJECTPATH/openhurricane

export PYTHONPATH=$PYTHONPATH:$SHOOTERPATH:$SPYPATH:$HURRICANEPATH

cd $CURRENTPATH
